/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ras.form;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import ras.RAS;
import ras.vlc.VLCPlaylistGenerator;
import sun.awt.image.FileImageSource;

/**
 *
 * @author Rafael
 */
public class RASMain extends javax.swing.JFrame {
    private static RAS ras;
    public static VLCPlaylistGenerator vpg; 
    private Image icon = createImage(new FileImageSource("../res/Logo.png"));           
    private Image bg = createImage(new FileImageSource("../res/Background.png"));           
     // Descomentar após implementar as outras funcionalidades
//        DefaultTableModel dtm = new DefaultTableModel(
//                null,
//                new String[]{
//                   "Título", "Nº Episódios", "Nº Vezes Assistido", "Nº Vezes Ignorado" 
//                });
//        
    private static DefaultTableModel dtm = new DefaultTableModel(
                new Object[][]{{"Diretório Vazio"}},
                new String[]{
                   "Título","Path"
                }){
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    private static File file;
    
    
    public DefaultTableModel getDTM(){
        return dtm;   
    }
    
    private static DefaultTableModel detModel = new DefaultTableModel(
                new Object[][]{{"Diretório Vazio"}},
                new String[]{
                   "Título","Nº de arquivos","Nº de diretórios","Path"
                }){
            boolean[] canEdit = new boolean [] {
                false,false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    public DefaultTableModel getDetModel(){
        return detModel;
    }
    /**
     * Creates new form RASMain
     */
    public RASMain() {
        VLCPlaylistGenerator vplg = new VLCPlaylistGenerator();
        initComponents();
//        this.setIconImage(icon);
        PanelImage pi;
        //
        List iconList = new ArrayList();
        iconList.add(icon);
        iconList.add(bg);
        this.setIconImages(iconList);
        pi = new PanelImage((Image)iconList.get(0));
        add(pi);
        pi = new PanelImage((Image)iconList.get(1));
        add(pi);
        this.setIconImages(iconList);
        ras = new RAS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        txtFolder = new javax.swing.JTextField();
        btnFolderSelector = new javax.swing.JButton();
        btnOpenFolder = new javax.swing.JButton();
        btnRandomSelect = new javax.swing.JButton();
        btnFolderDetail = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCarregarFolder = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        btnContinuarPlayList = new javax.swing.JButton();
        txtFiltrar = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnGeneratePlaylist = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblQtdResultados = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNadaAinda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAS - Random Anime Selector");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        txtFolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFolderKeyPressed(evt);
            }
        });

        btnFolderSelector.setBackground(new java.awt.Color(0, 0, 0));
        btnFolderSelector.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\Folder-Web-black-red (Custom) (Custom).PNG")); // NOI18N
        btnFolderSelector.setText("Browse");
        btnFolderSelector.setFocusable(false);
        btnFolderSelector.setOpaque(false);
        btnFolderSelector.setRequestFocusEnabled(false);
        btnFolderSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderSelectorActionPerformed(evt);
            }
        });

        btnOpenFolder.setBackground(new java.awt.Color(0, 0, 0));
        btnOpenFolder.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\Folder-black-red (Custom) (Custom).PNG")); // NOI18N
        btnOpenFolder.setToolTipText("Open Folder");
        btnOpenFolder.setOpaque(false);
        btnOpenFolder.setRequestFocusEnabled(false);
        btnOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFolderActionPerformed(evt);
            }
        });

        btnRandomSelect.setBackground(new java.awt.Color(0, 0, 0));
        btnRandomSelect.setText("Ramdom Select");
        btnRandomSelect.setAutoscrolls(true);
        btnRandomSelect.setOpaque(false);
        btnRandomSelect.setRequestFocusEnabled(false);
        btnRandomSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomSelectActionPerformed(evt);
            }
        });

        btnFolderDetail.setBackground(new java.awt.Color(0, 0, 0));
        btnFolderDetail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\File-Text-black-red (Custom) (Custom).PNG")); // NOI18N
        btnFolderDetail.setToolTipText("Folder Detail");
        btnFolderDetail.setOpaque(false);
        btnFolderDetail.setRequestFocusEnabled(false);
        btnFolderDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderDetailActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Exit");
        btnSair.setToolTipText("");
        btnSair.setOpaque(false);
        btnSair.setRequestFocusEnabled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCarregarFolder.setBackground(new java.awt.Color(0, 0, 0));
        btnCarregarFolder.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\Cd-Rom-black-red (Custom) (Custom).PNG")); // NOI18N
        btnCarregarFolder.setToolTipText("Load Folder");
        btnCarregarFolder.setOpaque(false);
        btnCarregarFolder.setRequestFocusEnabled(false);
        btnCarregarFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarFolderActionPerformed(evt);
            }
        });

        tabPane.setToolTipText("");

        tblLista.setModel(getDTM());
        tblLista.setToolTipText("");
        tblLista.setGridColor(new java.awt.Color(0, 0, 0));
        tblLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLista.getTableHeader().setReorderingAllowed(false);
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaMouseClicked(evt);
            }
        });
        tblLista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblListaFocusLost(evt);
            }
        });
        tblLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblListaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLista);
        tblLista.getAccessibleContext().setAccessibleName("");

        tabPane.addTab("Normal", jScrollPane1);

        tbDetail.setModel(getDetModel()        );
        tbDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbDetail.setEditingColumn(0);
        tbDetail.setEditingRow(0);
        tbDetail.setGridColor(new java.awt.Color(0, 0, 0));
        tbDetail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDetail.getTableHeader().setReorderingAllowed(false);
        tbDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDetailMouseClicked(evt);
            }
        });
        tbDetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbDetailFocusLost(evt);
            }
        });
        tbDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDetailKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDetail);

        tabPane.addTab("Detail", jScrollPane2);

        btnLimpar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\File-black-red (Custom) (Custom).PNG")); // NOI18N
        btnLimpar.setToolTipText("Clear");
        btnLimpar.setOpaque(false);
        btnLimpar.setRequestFocusEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnContinuarPlayList.setBackground(new java.awt.Color(0, 0, 0));
        btnContinuarPlayList.setText("Continue Playlist");
        btnContinuarPlayList.setToolTipText("Executa a última playlist gerada");
        btnContinuarPlayList.setOpaque(false);
        btnContinuarPlayList.setRequestFocusEnabled(false);
        btnContinuarPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarPlayListActionPerformed(evt);
            }
        });

        txtFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltrarActionPerformed(evt);
            }
        });
        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyPressed(evt);
            }
        });

        btnFiltrar.setBackground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setOpaque(false);
        btnFiltrar.setRequestFocusEnabled(false);
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnGeneratePlaylist.setBackground(new java.awt.Color(0, 0, 0));
        btnGeneratePlaylist.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\RAS\\res\\File-Media-black-red (Custom) (Custom).PNG")); // NOI18N
        btnGeneratePlaylist.setToolTipText("Generate Playlist");
        btnGeneratePlaylist.setAutoscrolls(true);
        btnGeneratePlaylist.setOpaque(false);
        btnGeneratePlaylist.setRequestFocusEnabled(false);
        btnGeneratePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePlaylistActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultados: ");

        lblQtdResultados.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtdResultados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lblQtdResultados))
        );

        jMenu1.setText("File");

        miNadaAinda.setText("Nada ainda");
        miNadaAinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNadaAindaActionPerformed(evt);
            }
        });
        jMenu1.add(miNadaAinda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFolderSelector))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRandomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContinuarPlayList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(btnGeneratePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpenFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCarregarFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFolderDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarregarFolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFolderDetail)
                    .addComponent(btnOpenFolder)
                    .addComponent(btnGeneratePlaylist)
                    .addComponent(btnLimpar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFolderSelector))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContinuarPlayList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRandomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        tabPane.getAccessibleContext().setAccessibleName("Normal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRandomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomSelectActionPerformed
        ras.randomSelect(vpg, file, txtFolder, tblLista, tbDetail);
    }//GEN-LAST:event_btnRandomSelectActionPerformed

    private void btnCarregarFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarFolderActionPerformed
        ras.loadFolder(dtm, detModel, txtFolder, file, tbDetail, tblLista,lblQtdResultados);
        file = new File(txtFolder.getText());
    }//GEN-LAST:event_btnCarregarFolderActionPerformed

    private void miNadaAindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNadaAindaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miNadaAindaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFolderDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderDetailActionPerformed
        // TODO add your handling code here        
        ras.getFolderDetail(dtm, tblLista, tbDetail);
    }//GEN-LAST:event_btnFolderDetailActionPerformed

    private void btnOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFolderActionPerformed
       ras.openFolder(tblLista, tbDetail);
    }//GEN-LAST:event_btnOpenFolderActionPerformed

    private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            btnOpenFolderActionPerformed(null);
        }
    }//GEN-LAST:event_tblListaMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void btnFolderSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderSelectorActionPerformed
        ras.folderSelector(txtFolder);
    }//GEN-LAST:event_btnFolderSelectorActionPerformed

    private void tbDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDetailMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            btnOpenFolderActionPerformed(null);
        }
    }//GEN-LAST:event_tbDetailMouseClicked

    private void tblListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListaKeyPressed
        // TODO add your handling code here:
        int linhaAtual = tblLista.getSelectedRow();
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnOpenFolderActionPerformed(null);          
            if(tblLista.getSelectedRow() >= 0)
                tblLista.setRowSelectionInterval(linhaAtual-1, linhaAtual-1);
        }
    }//GEN-LAST:event_tblListaKeyPressed

    private void tbDetailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDetailKeyPressed
        // TODO add your handling code here:
        int linhaAtual = tbDetail.getSelectedRow();
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnOpenFolderActionPerformed(null); 
            if(tbDetail.getSelectedRow() >= 0)
                    tbDetail.setRowSelectionInterval(linhaAtual-1, linhaAtual-1);
            else
                tbDetail.setRowSelectionInterval(linhaAtual, linhaAtual);
        }
    }//GEN-LAST:event_tbDetailKeyPressed
    private void tblListaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblListaFocusLost
    }//GEN-LAST:event_tblListaFocusLost

    private void tbDetailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbDetailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDetailFocusLost

    private void btnContinuarPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarPlayListActionPerformed
        // TODO add your handling code here:
        try{
            if(vpg == null){
                vpg = new VLCPlaylistGenerator();
            }
            File f = vpg.getLastPlaylist("./");
            if(f != null){
                java.awt.Desktop.getDesktop().open(f);
            }else{
                JOptionPane.showMessageDialog(null, "Não há playlist executada anteriormente!");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnContinuarPlayListActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        ArrayList<Object[]> filterRows;
        btnCarregarFolderActionPerformed(null);
        Object[] obj;
        if(tbDetail.getModel() != null && tbDetail.getRowCount() > 0
                && tblLista.getModel() != null && tblLista.getRowCount() > 0){
            filterRows = new ArrayList();
            for(int i = 0; i < tblLista.getModel().getRowCount(); i++){
                if(tblLista.getModel().getValueAt(i, 0).toString().toUpperCase().contains(txtFiltrar.getText().toUpperCase())){
                     obj = new Object[]{tblLista.getModel().getValueAt(i, 0), tblLista.getModel().getValueAt(i, 1)};
                    filterRows.add(obj);
                }
            }
            dtm.setRowCount(0);
            for(Object[] temp: filterRows){
                dtm.addRow(temp);
            }
            
            filterRows = new ArrayList();
            for(int i = 0; i < tbDetail.getModel().getRowCount(); i++){
                if(tbDetail.getModel().getValueAt(i, 0).toString().toUpperCase().contains(txtFiltrar.getText().toUpperCase())){
                    obj = new Object[]{tbDetail.getModel().getValueAt(i, 0), tbDetail.getModel().getValueAt(i, 1),tbDetail.getModel().getValueAt(i, 2),tbDetail.getModel().getValueAt(i, 3)};
                    filterRows.add(obj);
                }
            }
            lblQtdResultados.setText(String.valueOf(filterRows.size()));
            detModel.setRowCount(0);
            for(Object[] temp: filterRows){
                detModel.addRow(temp);
            }
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtFiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnFiltrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtFiltrarKeyPressed

    private void txtFolderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolderKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnCarregarFolderActionPerformed(null);
        }
    }//GEN-LAST:event_txtFolderKeyPressed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        detModel.setRowCount(0);
        txtFiltrar.setText("");
        txtFolder.setText("");
        lblQtdResultados.setText("0");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGeneratePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePlaylistActionPerformed
        // TODO add your handling code here:
        VLCPlaylistGenerator vpgs = new VLCPlaylistGenerator();
        String path;
        File f;
        if(tblLista.getSelectedRowCount() <=0 || !tblLista.isFocusOwner()){
            if(tbDetail.getSelectedRowCount() <= 0){
                JOptionPane.showMessageDialog(null,"Selecione uma linha!");
                return;
            }
            path = tbDetail.getValueAt(tbDetail.getSelectedRow(),3).toString();
            f = new File(path);
            
        }else{
            path = tblLista.getValueAt(tblLista.getSelectedRow(),1).toString();

            f = new File(path);
        }
        try {
                vpgs.generatePlaylist(f.getPath(), f.getName());
        } catch (Exception ex) {
                Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {     
            java.awt.Desktop.getDesktop().open(new File(vpgs.getPlayListPath()));
        } catch (IOException ex) {
            Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGeneratePlaylistActionPerformed

    private void txtFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RASMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RASMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RASMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RASMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(RASMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                RASMain main = new RASMain();                
                main.setLocationRelativeTo(null);
                main.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarFolder;
    private javax.swing.JButton btnContinuarPlayList;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFolderDetail;
    private javax.swing.JButton btnFolderSelector;
    private javax.swing.JButton btnGeneratePlaylist;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOpenFolder;
    private javax.swing.JButton btnRandomSelect;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQtdResultados;
    private javax.swing.JMenuItem miNadaAinda;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tbDetail;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtFiltrar;
    private javax.swing.JTextField txtFolder;
    // End of variables declaration//GEN-END:variables
}
